[project]
name = 'CryptoNews'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.CryptoNews]
path = 'contracts/CryptoNews.clar'
clarity_version = 3
epoch = 3.1

[contracts.ContentVerification]
path = 'contracts/ContentVerification.clar'
clarity_version = 3
epoch = 3.1

[contracts.EmergencyAlerts]
path = 'contracts/EmergencyAlerts.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
